# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifactorauth',
            name='phone_country_code',
            field=models.CharField(choices=[('+44', 'UK'), ('+1', 'US'), ('+506', 'Costa Rica')], default='+1', max_length=5, validators=[django.core.validators.RegexValidator(message='Please enter a valid country code.', regex='^(\\+?\\d{1,4})$')]),
        ),
    ]
